apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-server
  labels:
    app: express-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-server
  template:
    metadata:
      labels:
        app: express-server
    spec:
      containers:
      - name: simple-express
        image: ritaamro7/simple-express
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: express-server
  name: express-server-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/express-server-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: express-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
  
